/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controler.BLLKhachHang;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import object.KhachHang;
import object.TaoMa;

/**
 *
 * @author Nguyen Hoang Giang
 */
public class QuanLyKhachHangVIP extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHangVIP
     */
    private BLLKhachHang bllKhachHang;
    private DefaultTableModel dtmKhachHang;
    private SimpleDateFormat sdf;
    private TaoMa taoMa;
    private int sttCuoi;
    private String maTiepTheo;
    private int index;

    public QuanLyKhachHangVIP() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        khoiTaoDoiTuongVaGan();
        hienThiKhachHangLenBang(bllKhachHang.layToanBoKhachHangVip());
        lamSachDuLieuKhachHang();
        hienThiMaKhachHangTiepTheo();
    }

    private void khoiTaoDoiTuongVaGan() {
        index = 1;
        bllKhachHang = new BLLKhachHang();
        taoMa = new TaoMa();
        dtmKhachHang = new DefaultTableModel();
        dtmKhachHang.addColumn("Mã Khách Hàng");
        dtmKhachHang.addColumn("Tên Khách Hàng");
        dtmKhachHang.addColumn("Giới Tính");
        dtmKhachHang.addColumn("Năm Sinh");
        dtmKhachHang.addColumn("Số Điện Thoại");
        dtmKhachHang.addColumn("Số CMND");
        dtmKhachHang.addColumn("Địa Chỉ");

        sdf = new SimpleDateFormat("dd/MM/yyyy");
    }

    private void hienThiKhachHangLenBang(ArrayList<KhachHang> ds) {
        dtmKhachHang.setRowCount(0);
        for (KhachHang kh : ds) {
            Vector<String> v = new Vector<>();
            v.add(kh.getMaKhachHang());
            v.add(kh.getTen());
            v.add(kh.getGioiTinh());
            if (kh.getNamSinh() == null) {
                v.add("");
            } else {
                v.add(sdf.format(kh.getNamSinh()));
            }
            v.add(kh.getSoDienThoai());
            v.add(kh.getSoCMND());
            v.add(kh.getDiaChi());
            dtmKhachHang.addRow(v);
        }
        tblDanhSach.setModel(dtmKhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnKhachHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblMaKhachHangTiepTheo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rdKhachHangNam = new javax.swing.JRadioButton();
        rdKhachHangNu = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtSoCMNDKhachHang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSoDienThoaiKhachHang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDiaChiKhachHang = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserNamSinhKhachHang = new com.toedter.calendar.JDateChooser();
        btnTimKiemKhachHang = new javax.swing.JButton();
        btnThemKhachHang = new javax.swing.JButton();
        ThemKhachHangTuFile = new javax.swing.JButton();
        btnSuaKhachHang = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnXemToanBoKhachHang = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        chkSuDungMaKhachHangTiepTheo = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 670));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG VIP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(198, 198, 198))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnKhachHang.setBackground(new java.awt.Color(51, 204, 255));
        pnKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách Hàng:"));

        jLabel2.setText("Mã Khách Hàng:");

        jLabel11.setText("Mã Tiếp Theo:");

        lblMaKhachHangTiepTheo.setText("jLabel12");

        jLabel13.setText("Tên Khách Hàng:");

        jLabel14.setText("Giới Tính:");

        rdKhachHangNam.setBackground(new java.awt.Color(51, 204, 255));
        buttonGroup1.add(rdKhachHangNam);
        rdKhachHangNam.setText("Nam");

        rdKhachHangNu.setBackground(new java.awt.Color(51, 204, 255));
        buttonGroup1.add(rdKhachHangNu);
        rdKhachHangNu.setText("Nữ");

        jLabel15.setText("Số CMND:");

        jLabel16.setText("Số Điện Thoại:");

        jLabel17.setText("Địa Chỉ:");

        jLabel18.setText("Năm Sinh:");

        jDateChooserNamSinhKhachHang.setDateFormatString("dd/MM/yyyy");

        btnTimKiemKhachHang.setBackground(new java.awt.Color(51, 204, 255));
        btnTimKiemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Search-16.png"))); // NOI18N
        btnTimKiemKhachHang.setText("Tìm Kiếm");
        btnTimKiemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKhachHangActionPerformed(evt);
            }
        });

        btnThemKhachHang.setBackground(new java.awt.Color(51, 204, 255));
        btnThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Add-16.png"))); // NOI18N
        btnThemKhachHang.setText("Thêm");
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });

        ThemKhachHangTuFile.setBackground(new java.awt.Color(51, 204, 255));
        ThemKhachHangTuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Microsoft Excel-16.png"))); // NOI18N
        ThemKhachHangTuFile.setText("Thêm Từ File");
        ThemKhachHangTuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemKhachHangTuFileActionPerformed(evt);
            }
        });

        btnSuaKhachHang.setBackground(new java.awt.Color(51, 204, 255));
        btnSuaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Edit-16.png"))); // NOI18N
        btnSuaKhachHang.setText("Sửa");
        btnSuaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKhachHangActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(51, 204, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Broom-16.png"))); // NOI18N
        jButton14.setText("Làm Sạch Dữ Liệu Nhập");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        btnXemToanBoKhachHang.setBackground(new java.awt.Color(51, 204, 255));
        btnXemToanBoKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-select-all.png"))); // NOI18N
        btnXemToanBoKhachHang.setText("Xem Toàn Bộ");
        btnXemToanBoKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemToanBoKhachHangActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(51, 204, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Print-16.png"))); // NOI18N
        jButton16.setText("In Thông Tin");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        chkSuDungMaKhachHangTiepTheo.setBackground(new java.awt.Color(51, 204, 255));
        chkSuDungMaKhachHangTiepTheo.setText("Sử dụng mã tiếp theo");
        chkSuDungMaKhachHangTiepTheo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSuDungMaKhachHangTiepTheoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSoCMNDKhachHang)
                                    .addComponent(txtDiaChiKhachHang)))
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaKhachHang)
                                    .addComponent(lblMaKhachHangTiepTheo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTenKhachHang)
                                    .addComponent(jDateChooserNamSinhKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkSuDungMaKhachHangTiepTheo)
                                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                                .addComponent(rdKhachHangNam)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdKhachHangNu)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ThemKhachHangTuFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnKhachHangLayout.createSequentialGroup()
                                .addComponent(btnTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXemToanBoKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblMaKhachHangTiepTheo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSuDungMaKhachHangTiepTheo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdKhachHangNam)
                        .addComponent(rdKhachHangNu))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jDateChooserNamSinhKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSoCMNDKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtDiaChiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiemKhachHang)
                    .addComponent(btnThemKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThemKhachHangTuFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemToanBoKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách:"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDanhSachMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKhachHangActionPerformed
        // TODO add your handling code here:
        String maKhachHang = txtMaKhachHang.getText();
        String tenKhachHang = txtTenKhachHang.getText();
        String gioiTinh = "";
        if (rdKhachHangNam.isSelected()) {
            gioiTinh = "Nam";
        } else if (rdKhachHangNu.isSelected()) {
            gioiTinh = "Nữ";
        }
        Date namSinh = jDateChooserNamSinhKhachHang.getDate();
        String soCMND = txtSoCMNDKhachHang.getText();
        String soDienThoai = txtSoDienThoaiKhachHang.getText();
        String diaChi = txtDiaChiKhachHang.getText();
        if (kiemTraDuLieuNhapKhachHang(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi, "Tìm Kiếm")) {
            hienThiKhachHangLenBang(bllKhachHang.timKiemKhachHangVIP(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi));
        }
    }//GEN-LAST:event_btnTimKiemKhachHangActionPerformed

    private void hienThiMaKhachHangTiepTheo() {
        sttCuoi = taoMa.laySoCuoiCuaBangKhachHangVIP();
        maTiepTheo = "KHV" + taoMa.taoChuoiTuSoDaCho(sttCuoi);
        lblMaKhachHangTiepTheo.setText(maTiepTheo);
    }

    private boolean kiemTraDuLieuNhapKhachHang(String maKhachHang, String tenKhachHang, String gioiTinh, Date namSinh,
            String soCMND, String soDienThoai, String diaChi, String thaoTac) {
        String regex1 = "\\s*";
        String regex2 = "\\d{9}|\\d{12}";
        String regex3 = "\\d{10}|\\d{11}";
        if (maKhachHang.matches(regex1) && tenKhachHang.matches(regex1) && gioiTinh.matches(regex1) && namSinh == null
                && soCMND.matches(regex1) && soDienThoai.matches(regex1) && diaChi.matches(regex1)) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            return false;
        } else if (thaoTac.equalsIgnoreCase("Thêm")) {
            if (maKhachHang.matches(regex1)) {
                JOptionPane.showMessageDialog(null, "Chưa nhập mã khách hàng");
                return false;
            } else if (gioiTinh.matches(regex1)) {
                JOptionPane.showMessageDialog(null, "Chưa chọn giới tính");
                return false;
            }
        } else if (thaoTac.equals("Sửa")) {
            if (maKhachHang.matches(regex1)) {
                JOptionPane.showMessageDialog(null, "Chưa nhập mã khách hàng");
                return false;
            }
            int row = tblDanhSach.getSelectedRow();
            String maKhachHangGoc = tblDanhSach.getValueAt(row, 0) + "";
            if (!maKhachHang.equals(maKhachHangGoc)) {
                JOptionPane.showMessageDialog(null, "Không thể sửa mã khách hàng");
                txtMaKhachHang.setText(maKhachHangGoc);
                return false;
            }
        }
        if (!soCMND.matches(regex1) && !soCMND.matches(regex2)) {
            JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân phải là số có 9 hoặc 12 số");
            return false;
        } else if (!soDienThoai.matches(regex1) && !soDienThoai.matches(regex3)) {
            JOptionPane.showMessageDialog(null, "Số điện thoại phải là số có 10 hoặc 11 số");
            return false;
        }
        return true;
    }

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        // TODO add your handling code here:
        String maKhachHang = lblMaKhachHangTiepTheo.getText();
        if (chkSuDungMaKhachHangTiepTheo.isSelected() == false) {
            maKhachHang = txtMaKhachHang.getText();
        }
        String tenKhachHang = txtTenKhachHang.getText();
        String gioiTinh = "";
        if (rdKhachHangNam.isSelected()) {
            gioiTinh = "Nam";
        } else if (rdKhachHangNu.isSelected()) {
            gioiTinh = "Nữ";
        }
        Date namSinh = jDateChooserNamSinhKhachHang.getDate();
        String soCMND = txtSoCMNDKhachHang.getText();
        String soDienThoai = txtSoDienThoaiKhachHang.getText();
        String diaChi = txtDiaChiKhachHang.getText();
        if (kiemTraDuLieuNhapKhachHang(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi, "Thêm")) {
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm khách hàng ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (xacNhan != JOptionPane.YES_OPTION) {
                return;
            }
            if (bllKhachHang.themKhachHangVIP(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                lamSachDuLieuKhachHang();
                hienThiMaKhachHangTiepTheo();
                hienThiKhachHangLenBang(bllKhachHang.layToanBoKhachHangVip());
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    private void lamSachDuLieuKhachHang() {
        txtMaKhachHang.setText("");
        txtTenKhachHang.setText("");
        if (rdKhachHangNam.isSelected()) {
            rdKhachHangNam.setSelected(false);
        } else {
            rdKhachHangNu.setSelected(false);
        }
        jDateChooserNamSinhKhachHang.setDate(null);
        txtSoCMNDKhachHang.setText("");
        txtSoDienThoaiKhachHang.setText("");
        txtDiaChiKhachHang.setText("");
    }

    private void ThemKhachHangTuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemKhachHangTuFileActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Chức năng đang cập nhật");
    }//GEN-LAST:event_ThemKhachHangTuFileActionPerformed

    private void btnSuaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKhachHangActionPerformed
        // TODO add your handling code here:
        String maKhachHang = txtMaKhachHang.getText();
        String tenKhachHang = txtTenKhachHang.getText();
        String gioiTinh = "";
        if (rdKhachHangNam.isSelected()) {
            gioiTinh = "Nam";
        } else if (rdKhachHangNu.isSelected()) {
            gioiTinh = "Nữ";
        }
        Date namSinh = jDateChooserNamSinhKhachHang.getDate();
        String soCMND = txtSoCMNDKhachHang.getText();
        String soDienThoai = txtSoDienThoaiKhachHang.getText();
        String diaChi = txtDiaChiKhachHang.getText();
        if (kiemTraDuLieuNhapKhachHang(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi, "Sửa")) {
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa khách hàng ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (xacNhan == JOptionPane.YES_OPTION) {
                if (bllKhachHang.suaKhachHangVIP(maKhachHang, tenKhachHang, gioiTinh, namSinh, soCMND, soDienThoai, diaChi) > 0) {
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    lamSachDuLieuKhachHang();
                    hienThiKhachHangLenBang(bllKhachHang.layToanBoKhachHangVip());
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnSuaKhachHangActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        lamSachDuLieuKhachHang();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnXemToanBoKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemToanBoKhachHangActionPerformed
        // TODO add your handling code here:
        hienThiKhachHangLenBang(bllKhachHang.layToanBoKhachHangVip());
    }//GEN-LAST:event_btnXemToanBoKhachHangActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Chức năng đang cập nhật");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void chkSuDungMaKhachHangTiepTheoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSuDungMaKhachHangTiepTheoStateChanged
        // TODO add your handling code here:
        if (chkSuDungMaKhachHangTiepTheo.isSelected()) {
            txtMaKhachHang.setEditable(false);
        } else {
            txtMaKhachHang.setEditable(true);
        }
    }//GEN-LAST:event_chkSuDungMaKhachHangTiepTheoStateChanged

    private void tblDanhSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMousePressed
        // TODO add your handling code here:
        dienThongTinKhachHang();
    }//GEN-LAST:event_tblDanhSachMousePressed

    private void dienThongTinKhachHang() {
        try {
            int row = tblDanhSach.getSelectedRow();
            txtMaKhachHang.setText(tblDanhSach.getValueAt(row, 0) + "");
            txtTenKhachHang.setText(tblDanhSach.getValueAt(row, 1) + "");
            String gioiTinh = tblDanhSach.getValueAt(row, 2) + "";
            if (gioiTinh.equals("Nam")) {
                rdKhachHangNam.setSelected(true);
            } else {
                rdKhachHangNu.setSelected(true);
            }
            Date namSinh = null;
            String strNamSinh = tblDanhSach.getValueAt(row, 3) + "";
            if (!strNamSinh.equals("")) {
                namSinh = sdf.parse(strNamSinh);
            }
            jDateChooserNamSinhKhachHang.setDate(namSinh);
            txtSoDienThoaiKhachHang.setText(tblDanhSach.getValueAt(row, 4) + "");
            txtSoCMNDKhachHang.setText(tblDanhSach.getValueAt(row, 5) + "");
            txtDiaChiKhachHang.setText(tblDanhSach.getValueAt(row, 6) + "");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHangVIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThemKhachHangTuFile;
    private javax.swing.JButton btnSuaKhachHang;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JButton btnTimKiemKhachHang;
    private javax.swing.JButton btnXemToanBoKhachHang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkSuDungMaKhachHangTiepTheo;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private com.toedter.calendar.JDateChooser jDateChooserNamSinhKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaKhachHangTiepTheo;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JRadioButton rdKhachHangNam;
    private javax.swing.JRadioButton rdKhachHangNu;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDiaChiKhachHang;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoCMNDKhachHang;
    private javax.swing.JTextField txtSoDienThoaiKhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
