/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controler.BLLBanHang;
import controler.BLLCacChiPhiKhac;
import controler.BLLDiaNhac;
import controler.BLLDiaPhim;
import controler.BLLNhanVien;
import controler.BLLSach;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.QueryNhanVien;
import object.CacChiPhiKhac;
import object.DiaNhac;
import object.DiaPhim;
import object.NhanVien;
import object.NhanVienChinhThuc;
import object.NhanVienThoiVu;
import object.QuanLy;
import object.Sach;
import object.SanPham;

/**
 *
 * @author kiendt
 */
public class ThongKe extends javax.swing.JFrame {

    double tongLuongNhanVien = 0;
    double tongChiPhiKhac = 0;
    double tongTienNhapHang = 0;
    double tongTienXuatHang = 0;
    double tongTienMuaSanPhamDaBan = 0;
    private int index;
    private BLLNhanVien bllNhanVien;
    private BLLSach bllSach;
    private BLLDiaNhac bLLDiaNhac;
    private BLLDiaPhim bllDiaPhim;
    private BLLBanHang bllBanHang;
    private BLLCacChiPhiKhac bllCacChiPhiKhac;
    private DefaultTableModel dtmNhanVien;
    private DefaultTableModel dtmCacChiPhiKhac;
    private DefaultTableModel dtmSanPham;
    private DefaultTableModel dtmSanPhamBan;
    private SimpleDateFormat sdf;
    private QuanLy quanLy;
    private ArrayList<SanPham> sanPhamNhap;
    private ArrayList<SanPham> sanPhamBan;

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        khoiTaoDoiTuong();
        jComboBox_kieuTimKiem.setSelectedItem("Thống kê theo ngày");
        Date date_now = new Date();
        jthongKeTheoNgay.setDate(date_now);
    }

    private void khoiTaoDoiTuong() {
        bllNhanVien = new BLLNhanVien();
        bllSach = new BLLSach();
        bLLDiaNhac = new BLLDiaNhac();
        bllDiaPhim = new BLLDiaPhim();
        bllBanHang = new BLLBanHang();
        bllCacChiPhiKhac = new BLLCacChiPhiKhac();
        sanPhamNhap = new ArrayList<SanPham>();
        sanPhamBan = new ArrayList<SanPham>();
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        quanLy = new QuanLy();
        NhanVienChinhThuc.tienLamMotNgay = bllNhanVien.tienLamMotNgay("CT");
        NhanVienChinhThuc.tienLamThemMotNgay = bllNhanVien.tienThemLamMotNgay("CT");
        NhanVienThoiVu.tienLamMotNgay = bllNhanVien.tienLamMotNgay("TV");
        NhanVienThoiVu.tienLamThemMotNgay = bllNhanVien.tienThemLamMotNgay("TV");

        dtmNhanVien = new DefaultTableModel();
        dtmNhanVien.addColumn("Mã Nhân Viên");
        dtmNhanVien.addColumn("Tên Nhân Viên");
        dtmNhanVien.addColumn("Lương");

        dtmCacChiPhiKhac = new DefaultTableModel();
        dtmCacChiPhiKhac.addColumn("Loại Chi Phí");
        dtmCacChiPhiKhac.addColumn("Ngày");
        dtmCacChiPhiKhac.addColumn("Tiền");

        dtmSanPham = new DefaultTableModel();
        dtmSanPham.addColumn("Tên sản phẩm");
        dtmSanPham.addColumn("Loại");
        dtmSanPham.addColumn("Giá mua");
        dtmSanPham.addColumn("Số lượng");

        dtmSanPhamBan = new DefaultTableModel();
        dtmSanPhamBan.addColumn("Tên sản phẩm");
        dtmSanPhamBan.addColumn("Loại");
        dtmSanPhamBan.addColumn("Giá mua");
        dtmSanPhamBan.addColumn("Giá bán");
        dtmSanPhamBan.addColumn("Số lượng");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_kieuTimKiem = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_thang = new javax.swing.JComboBox<>();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jthongKeTheoNgay = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser_start = new com.toedter.calendar.JDateChooser();
        jDateChooser_end = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tongChiPhiPhatSinh = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_luongNhanVien = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel_tongLuongNhanVien = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_tongChiPhiPhatSinh = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_hangNhapVe = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_hangXuat = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel_doanhThu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_tongTienChi = new javax.swing.JLabel();
        jLabel_tongTienBanSanPham = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Kiểu thông kê ");

        jComboBox_kieuTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê theo ngày", "Thống kê theo tháng", "Thống kê theo năm", "Thống kê trong 1 khoảng thời gian" }));
        jComboBox_kieuTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_kieuTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Tháng : ");

        jComboBox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setText("Năm : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel4.setText("Năm : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jYearChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel12.setText("Ngày : ");

        jthongKeTheoNgay.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jthongKeTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jthongKeTheoNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel15.setText("Từ   :");

        jLabel16.setText("Đến  :");

        jDateChooser_start.setDateFormatString("dd/MM/yyyy");

        jDateChooser_end.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_end, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blocks_gnome_netstatus_50_74.png"))); // NOI18N
        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable_tongChiPhiPhatSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại chi phí", "Ngày chi", "Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_tongChiPhiPhatSinh);

        jTable_luongNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_luongNhanVien);
        if (jTable_luongNhanVien.getColumnModel().getColumnCount() > 0) {
            jTable_luongNhanVien.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        jLabel9.setText("Tổng lương nhân viên : ");

        jLabel_tongLuongNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tongLuongNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Tổng chi phí phát sinh : ");

        jLabel_tongChiPhiPhatSinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tongChiPhiPhatSinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable_hangNhapVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Loại", "Đơn giá/sản phẩm", "Số lượng đã nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_hangNhapVe);
        if (jTable_hangNhapVe.getColumnModel().getColumnCount() > 0) {
            jTable_hangNhapVe.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        jTable_hangXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Loại", "Giá bán/sản phẩm", "Số lượng đã xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_hangXuat);
        if (jTable_hangXuat.getColumnModel().getColumnCount() > 0) {
            jTable_hangXuat.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_tongLuongNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_tongChiPhiPhatSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tongChiPhiPhatSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tongLuongNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Doanh thu cửa hàng : ");

        jLabel_doanhThu.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_doanhThu.setForeground(java.awt.Color.red);
        jLabel_doanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_doanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Tổng tiền chi mua sản phẩm : ");

        jLabel_tongTienChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tongTienChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_tongTienBanSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tongTienBanSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Tổng tiền bán sản phẩm : ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Lợi nhuận cửa hàng:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_kieuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_doanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextField1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_tongTienChi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_tongTienBanSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox_kieuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_doanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tongTienBanSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tongTienChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blocks_gnome_netstatus_50_74.png"))); // NOI18N
        jMenu1.setText("Thống kê");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_kieuTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_kieuTimKiemActionPerformed
        System.out.println("Vào");
        String kieuTimKiem = jComboBox_kieuTimKiem.getSelectedItem().toString();
        switch (kieuTimKiem) {
            case "Thống kê theo ngày":
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel7.setVisible(true);
                jPanel6.setVisible(false);
                index = 1;
                break;
            case "Thống kê theo tháng":
                jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                jPanel7.setVisible(false);
                jPanel6.setVisible(false);
                index = 2;
                break;
            case "Thống kê theo năm":
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                jPanel7.setVisible(false);
                jPanel6.setVisible(false);
                index = 3;
                break;
            case "Thống kê trong 1 khoảng thời gian":
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel7.setVisible(false);
                jPanel6.setVisible(true);
                index = 4;
                break;
        }
    }//GEN-LAST:event_jComboBox_kieuTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (index) {
            case 1:
                thongKeTheoNgay();
                break;
            case 2:
                thongKeTheoThang();
                break;
            case 3:
                thongKeTheoNam();
                break;
            case 4:
                thongKeTrongKhoanMotThoiGian();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void thongKeTheoNgay() {
        Date ngay = jthongKeTheoNgay.getDate();
        ArrayList<NhanVien> dsNhanVien = bllNhanVien.nhanVienTraLuong(ngay);
        hienNhanVienLenBang(dsNhanVien);
        jLabel_tongLuongNhanVien.setText(quanLy.tinhTongLuongNhanVien(dsNhanVien) + " VND");
        ArrayList<CacChiPhiKhac> dsChiPhi = bllCacChiPhiKhac.thongKeTheoNgay(ngay);
        hienChiPhiKhacLenBang(dsChiPhi);
        jLabel_tongChiPhiPhatSinh.setText(quanLy.tinhTongCacChiPhiKhac(dsChiPhi) + " VND");

        sanPhamBan = bllBanHang.sanPhamBanNgay(ngay);
        hienThiSanPhamBanLenBang(sanPhamBan);
        jLabel_tongTienChi.setText(quanLy.tinhTongGiaMuaSanPham(sanPhamNhap) + " VND");
        jLabel_tongTienBanSanPham.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jLabel_doanhThu.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jTextField1.setText(quanLy.tinhLoiNhuan(dsNhanVien, sanPhamNhap, sanPhamBan, dsChiPhi) + " VND");
    }

    private void hienThiSanPhamLenBang(ArrayList<SanPham> ds) {
        if (ds != null) {
            dtmSanPham.setRowCount(0);
            for (SanPham sp : ds) {
                Vector<String> v = new Vector<>();
                v.add(sp.getTenSanPham());
                if (sp instanceof Sach) {
                    v.add("Sách");
                } else if (sp instanceof DiaNhac) {
                    v.add("Đĩa nhạc");
                } else {
                    v.add("Đĩa phim");
                }
                v.add(sp.getGiaMua() + " VND");
                v.add(sp.getSoLuong() + "");
                dtmSanPham.addRow(v);
            }
            jTable_hangNhapVe.setModel(dtmSanPham);
        }
    }

    private void hienThiSanPhamBanLenBang(ArrayList<SanPham> ds) {
        if (ds != null) {
            dtmSanPhamBan.setRowCount(0);
            for (SanPham sp : ds) {
                Vector<String> v = new Vector<>();
                v.add(sp.getTenSanPham());
                if (sp instanceof Sach) {
                    v.add("Sách");
                } else if (sp instanceof DiaNhac) {
                    v.add("Đĩa nhạc");
                } else {
                    v.add("Đĩa phim");
                }
                v.add(sp.getGiaMua() + " VND");
                v.add(sp.getGiaBan() + " VND");
                v.add(sp.getSoLuong() + "");
                dtmSanPhamBan.addRow(v);
            }
            jTable_hangXuat.setModel(dtmSanPhamBan);
        }
    }

    private void thongKeTrongKhoanMotThoiGian() {
        Date ngayMin = jDateChooser_start.getDate();
        Date ngayMax = jDateChooser_end.getDate();
        ArrayList<NhanVien> dsNhanVien = bllNhanVien.nhanVienTraLuong(ngayMin, ngayMax);
        hienNhanVienLenBang(dsNhanVien);
        jLabel_tongLuongNhanVien.setText(quanLy.tinhTongLuongNhanVien(dsNhanVien) + " VND");
        ArrayList<CacChiPhiKhac> dsChiPhi = bllCacChiPhiKhac.thongKeTheoNgay(ngayMin, ngayMax);
        hienChiPhiKhacLenBang(dsChiPhi);
        jLabel_tongChiPhiPhatSinh.setText(quanLy.tinhTongCacChiPhiKhac(dsChiPhi) + " VND");
        ArrayList<Sach> sachNhap = bllSach.sachNhapNgay(ngayMin, ngayMax);
        ArrayList<DiaNhac> diaNhacNhap = bLLDiaNhac.diaNhacNhapNgay(ngayMin, ngayMax);
        ArrayList<DiaPhim> diaPhimNhap = bllDiaPhim.diaPhimNhapNgay(ngayMin, ngayMax);
        sanPhamNhap.clear();
        for (Sach s : sachNhap) {
            sanPhamNhap.add(s);
        }
        for (DiaNhac d : diaNhacNhap) {
            sanPhamNhap.add(d);
        }
        for (DiaPhim d : diaPhimNhap) {
            sanPhamNhap.add(d);
        }
        hienThiSanPhamLenBang(sanPhamNhap);
        sanPhamBan = bllBanHang.sanPhamBanNgay(ngayMin, ngayMax);
        hienThiSanPhamBanLenBang(sanPhamBan);
        jLabel_tongTienChi.setText(quanLy.tinhTongGiaMuaSanPham(sanPhamNhap) + " VND");
        jLabel_tongTienBanSanPham.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jLabel_doanhThu.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jTextField1.setText(quanLy.tinhLoiNhuan(dsNhanVien, sanPhamNhap, sanPhamBan, dsChiPhi) + " VND");
    }

    private void thongKeTheoThang() {
        try {
            String strThang = jComboBox_thang.getSelectedItem().toString();
            int thang = Integer.parseInt(strThang);
            int nam = jYearChooser1.getValue();
            ArrayList<NhanVien> dsNhanVien = bllNhanVien.thongKeNhanVienTheoThang(thang, nam);
            hienNhanVienLenBang(dsNhanVien);
            jLabel_tongLuongNhanVien.setText(quanLy.tinhTongLuongNhanVien(dsNhanVien) + " VND");
            ArrayList<CacChiPhiKhac> dsCacChiPhi = bllCacChiPhiKhac.thongKeTheoThangNam(thang, nam);
            hienChiPhiKhacLenBang(dsCacChiPhi);
            jLabel_tongChiPhiPhatSinh.setText(quanLy.tinhTongCacChiPhiKhac(dsCacChiPhi) + " VND");
            ArrayList<Sach> sachNhap = bllSach.sachNhapThangNam(thang, nam);
            ArrayList<DiaNhac> diaNhacNhap = bLLDiaNhac.diaNhacNhapThangNam(thang, nam);
            ArrayList<DiaPhim> diaPhimNhap = bllDiaPhim.diaPhimNhapThangNam(thang, nam);
            sanPhamNhap.clear();
            for (Sach s : sachNhap) {
                sanPhamNhap.add(s);
            }
            for (DiaNhac d : diaNhacNhap) {
                sanPhamNhap.add(d);
            }
            for (DiaPhim d : diaPhimNhap) {
                sanPhamNhap.add(d);
            }
            hienThiSanPhamLenBang(sanPhamNhap);

            sanPhamBan = bllBanHang.sanPhamBanThang(thang, nam);
            hienThiSanPhamBanLenBang(sanPhamBan);
            jLabel_tongTienChi.setText(quanLy.tinhTongGiaMuaSanPham(sanPhamNhap) + " VND");
            jLabel_tongTienBanSanPham.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
            jLabel_doanhThu.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
            jTextField1.setText(quanLy.tinhLoiNhuan(dsNhanVien, sanPhamNhap, sanPhamBan, dsCacChiPhi) + " VND");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void thongKeTheoNam() {
        int nam = jYearChooser2.getValue();
        ArrayList<NhanVien> dsNhanVien = bllNhanVien.thongKeNhanVienTheoNam(nam);
        hienNhanVienLenBang(dsNhanVien);
        jLabel_tongLuongNhanVien.setText(quanLy.tinhTongLuongNhanVien(dsNhanVien) + " VND");
        ArrayList<CacChiPhiKhac> dsChiPhiKhac = bllCacChiPhiKhac.thongKeTheoNam(nam);
        hienChiPhiKhacLenBang(dsChiPhiKhac);
        jLabel_tongChiPhiPhatSinh.setText(quanLy.tinhTongCacChiPhiKhac(dsChiPhiKhac) + " VND");
        ArrayList<Sach> sachNhap = bllSach.sachNhapNam(nam);
        ArrayList<DiaNhac> diaNhacNhap = bLLDiaNhac.diaNhacNhapNam(nam);
        ArrayList<DiaPhim> diaPhimNhap = bllDiaPhim.diaPhimNhapNam(nam);
        sanPhamNhap.clear();
        for (Sach s : sachNhap) {
            sanPhamNhap.add(s);
        }
        for (DiaNhac d : diaNhacNhap) {
            sanPhamNhap.add(d);
        }
        for (DiaPhim d : diaPhimNhap) {
            sanPhamNhap.add(d);
        }
        hienThiSanPhamLenBang(sanPhamNhap);

        sanPhamBan = bllBanHang.sanPhamBanNam(nam);
        hienThiSanPhamBanLenBang(sanPhamBan);
        jLabel_tongTienChi.setText(quanLy.tinhTongGiaMuaSanPham(sanPhamNhap) + " VND");
        jLabel_tongTienBanSanPham.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jLabel_doanhThu.setText(quanLy.tinhTongGiaBanSanPham(sanPhamBan) + " VND");
        jTextField1.setText(quanLy.tinhLoiNhuan(dsNhanVien, sanPhamNhap, sanPhamBan, dsChiPhiKhac) + " VND");
    }

    private void hienNhanVienLenBang(ArrayList<NhanVien> ds) {
        if (ds != null) {
            dtmNhanVien.setRowCount(0);
            for (NhanVien nv : ds) {
                Vector<String> v = new Vector<>();
                v.add(nv.getMaNhanVien());
                v.add(nv.getTen());
                v.add(nv.tinhLuong() + " VND");
                dtmNhanVien.addRow(v);
            }
            jTable_luongNhanVien.setModel(dtmNhanVien);
        }
    }

    private void hienChiPhiKhacLenBang(ArrayList<CacChiPhiKhac> ds) {
        if (ds != null) {
            dtmCacChiPhiKhac.setRowCount(0);
            for (CacChiPhiKhac c : ds) {
                Vector<String> v = new Vector<>();
                v.add(c.getLoaiChiPhi());
                v.add(sdf.format(c.getNgay()));
                v.add(c.getTienTra() + " VND");
                dtmCacChiPhiKhac.addRow(v);
            }
            jTable_tongChiPhiPhatSinh.setModel(dtmCacChiPhiKhac);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_kieuTimKiem;
    private javax.swing.JComboBox<String> jComboBox_thang;
    private com.toedter.calendar.JDateChooser jDateChooser_end;
    private com.toedter.calendar.JDateChooser jDateChooser_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_doanhThu;
    private javax.swing.JLabel jLabel_tongChiPhiPhatSinh;
    private javax.swing.JLabel jLabel_tongLuongNhanVien;
    private javax.swing.JLabel jLabel_tongTienBanSanPham;
    private javax.swing.JLabel jLabel_tongTienChi;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_hangNhapVe;
    private javax.swing.JTable jTable_hangXuat;
    private javax.swing.JTable jTable_luongNhanVien;
    private javax.swing.JTable jTable_tongChiPhiPhatSinh;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private com.toedter.calendar.JDateChooser jthongKeTheoNgay;
    // End of variables declaration//GEN-END:variables

    private void thongKeGiuaHaiThang() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
